name: Verify
on: [push, pull_request]
jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check bash formatting with shfmt (https://github.com/patrickvane/shfmt)
      - name: bash formatting
        run: docker run -v "$PWD":/mnt -w /mnt mvdan/shfmt -ci -i 2 -l -d -- *.sh

      # Analyse bash with ShellCheck (https://github.com/koalaman/shellcheck)
      - name: shellcheck
        run: docker run -v "$PWD":/mnt -w /mnt koalaman/shellcheck -- *.sh test/*.bats

      # Check other files formatting with Prettier (https://prettier.io)
      - name: misc files formatting
        run: docker run -v "$PWD":/mnt -w /mnt tmknom/prettier --check .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/panubo/setup-bats-action
      - name: Setup Bats
        uses: panubo/setup-bats-action@v2
        with:
          bats-version: 1.9.0

      # https://github.com/brokenpip3/setup-bats-libs
      - name: Setup Bats libraries
        uses: brokenpip3/setup-bats-libs@1.0.0
        with:
          support-path: ${{ github.workspace }}/test/test_helper/bats-support
          assert-path: ${{ github.workspace }}/test/test_helper/bats-assert
          detik-install: false
          file-install: false

      - name: Run Tests
        run: bats --trace --print-output-on-failure test/
